spring:
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: user
    password: passw0rd
  flyway:
    enabled: true
    default-schema: library
    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        default_schema: library
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        max-page-size: 100
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:1b
logging:
  level:
    org.springframework.web: DEBUG
springdoc:
  override-with-generic-response: false
